name: Memory Server CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    name: Build, Test, Native, and Push Image
    runs-on: ubuntu-latest

    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      REGISTRY: ghcr.io
      IMAGE_NAME: ghcr.io/lucienbrule/memory-server

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'graalvm'
          cache: 'gradle'

      - name: Grant execute permission to Gradle wrapper
        run: chmod +x ./gradlew

      - name: Run unit tests
        run: ./gradlew test

      #      - name: Run integration tests TODO: don't use the openai api key in intTest, create a profile.
      #        run: ./gradlew intTest

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build native container image with Docker
        run: |
          ./gradlew build \
            -Dquarkus.native.enabled=true \
            -Dquarkus.native.container-build=true \
            -Dquarkus.native.builder-image=graalvm \
            -Dquarkus.package.type=native \
            -Dquarkus.container-image.build=true \
            -Dquarkus.container-image.image=${{ env.IMAGE_NAME }} \
            -Dquarkus.container-image.push=true

      - name: Mirror to Artifact Registry
        run: |
          docker pull ${{ env.IMAGE_NAME }}
          docker tag \
            ghcr.io/lucienbrule/memory-server:${{ github.sha }} \
            us-central1-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/memory-server-repo/memory-server:${{ github.sha }}
          docker push \
            us-central1-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/memory-server-repo/memory-server:${{ github.sha }}