name: Memory Server CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    name: Build, Test, Native, and Push Image
    runs-on: ubuntu-latest

    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      REGISTRY: ghcr.io
      IMAGE_NAME: ghcr.io/lucienbrule/memory-server
      GCR_REGISTRY: us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}
      GCR_REPOSITORY: memory-server-repo/memory-server

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'graalvm'
          cache: 'gradle'

      - name: Grant execute permission to Gradle wrapper
        run: chmod +x ./gradlew

      - name: Run unit tests
        run: ./gradlew test

      #      - name: Run integration tests TODO: don't use the openai api key in intTest, create a profile.
      #        run: ./gradlew intTest

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Install & configure gcloud
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          install_components: docker-credential-gcr

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

      - name: Set up IMAGE_TAG
        shell: bash
        run: echo "IMAGE_TAG=${GITHUB_SHA:0:8}" >> $GITHUB_ENV

      - name: Build native container image with Docker
        run: |
          ./gradlew build \
            -Dquarkus.native.enabled=true \
            -Dquarkus.native.container-build=true \
            -Dquarkus.native.builder-image=graalvm \
            -Dquarkus.package.type=native \
            -Dquarkus.container-image.build=true \
            -Dquarkus.container-image.image=${{env.IMAGE_NAME}}:${{env.IMAGE_TAG}} \
            -Dquarkus.container-image.additional-tags=latest \
            -Dquarkus.container-image.push=true

      - name: Mirror to Artifact Registry
        run: |
          # Pull the GHCR image by shor-SHA
          docker pull ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

          # Tag & push short-SHA into Artifact Registry
          docker tag \
            ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} \
            ${{ env.GCR_REGISTRY }}/${{ env.GCR_REPOSITORY }}:${{ env.IMAGE_TAG }}
          docker push \
            ${{ env.GCR_REGISTRY }}/${{ env.GCR_REPOSITORY }}:${{ env.IMAGE_TAG }}

          # Also tag & push as latest
          docker tag \
            ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} \
            ${{ env.GCR_REGISTRY }}/${{ env.GCR_REPOSITORY }}:latest
          docker push \
            ${{ env.GCR_REGISTRY }}/${{ env.GCR_REPOSITORY }}:latest