

name: Deploy to Cloud Run

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Native Container to Cloud Run
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    needs: build-and-push

    steps:
      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: memory-server
          region: us-central1
          image: ghcr.io/lucienbrule/memory-server:${{ github.sha }}