name: Build & Publish Native Binaries

on:
  push:
    tags:
      - 'v*'       # only on version tags

permissions:
  contents: write

jobs:
  build-and-upload:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        module: [memory-cli, memory-proxy, memory-server]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'graalvm'

      - run: chmod +x ./gradlew

      - name: Build native runner
        run: |
          ./gradlew :${{ matrix.module }}:build \
            -x test -x intTest \
            -Dquarkus.native.enabled=true \
            -Dquarkus.package.jar.enabled=false

      - name: Set PLATFORM & VERSION
        run: |
          # map GHOS to platform
          if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            echo "PLATFORM=linux-x86_64" >> $GITHUB_ENV
          else
            echo "PLATFORM=darwin-arm64" >> $GITHUB_ENV
          fi
          # strip refs/tags/
          VERSION=${GITHUB_REF#refs/tags/}
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Rename runner with version & arch
        run: |
          SRC="${{ matrix.module }}/build/${{ matrix.module }}-runner"
          DST="${{ matrix.module }}/build/${{ matrix.module }}-${{env.VERSION}}-${{env.PLATFORM}}"
          mv "$SRC" "$DST"

      - name: Upload runner as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.module }}-${{env.PLATFORM}}
          path: ${{ matrix.module }}/build/${{ matrix.module }}-${{env.VERSION}}-${{env.PLATFORM}}

  publish:
    needs: build-and-upload
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Download all runners
        uses: actions/download-artifact@v4
        with:
          path: runners
          merge-multiple: true   # flattens into runners/

      - name: Create Release & upload binaries
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          artifacts: runners/*   # picks up all six uniquely-named files