name: Build & Publish Native Binaries

on:
  push:
    tags:
      - 'v*'       # only on version tags

permissions:
  contents: write

jobs:
  build-and-upload:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        module: [memory-cli, memory-proxy, memory-server]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up GraalVM
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'graalvm'

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Build native runner
        run: |
          ./gradlew :${{ matrix.module }}:build \
            -x test -x intTest \
            -Dquarkus.native.enabled=true \
            -Dquarkus.package.jar.enabled=false

      - name: Upload runner as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.module }}-${{github.ref_name}}-${{ matrix.os }}
          path: ${{ matrix.module }}/build/${{ matrix.module }}-runner

  publish:
    needs: build-and-upload
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download all runners
        uses: actions/download-artifact@v4
        with:
          path: runners
          merge-multiple: true

      - name: Create Release & upload binaries
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          artifacts: runners/*